### ISSUE TITLE
Reduce Github Permissions

### ISSUE THREAD

**Issue by joshuaquek** [flxwu/maintainerswanted.com#46]
When I tried to authorize my github account on maintainerswanted.com, it was asking for access for my private repos, as well as my personal github details.

Would it be possible to reduce the permissions to only access public repos and public personal information? 

I am not allowed to share some of the private repos that I have access to, due to professional reasons.
Also, there is no need for maintainerswanted to access private personal github information.

**Comment by flxwu** [comment]
You're absolutely right, thanks a lot for noting! 🙏👍 We are working on some major additions (see #17) that refactor&restructure the codebase quite a bit anyway that we will be pushing to production in a few days. 

I still agree with you that maintainerswanted has no use for accessing private repos! It'd be cool if you could open a PR for that, see the github auth scopes for the `api/auth/github` route in [`routes/auth.js`](https://github.com/flxwu/maintainerswanted.com/blob/master/routes/auth.js)

**Comment by flxwu** [comment]
Fixed @joshuaquek :)

**Comment by joshuaquek** [comment]
Alright, thanks!

**Comment by joshuaquek** [comment]
@flxwu would it be possible to also reduce permissions for user profile? Now it has Read AND Write access to the user's profile. It should only be able to READ but not WRITE or change the user's profile information.

**Comment by joshuaquek** [comment]
(should I open a new issue for this?)

**Comment by flxwu** [comment]
Right, thanks a lot for noting! just fixed that :P now it only requests `read:user, public_repo,admin:repo_hook`, see https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/ 😄 You can now add your project if you want!
